# Generated by Django 4.1.6 on 2023-02-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ardas_Interior_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
